# Generated by Django 5.2.1 on 2025-05-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='available_course_levels',
        ),
        migrations.RemoveField(
            model_name='university',
            name='fields_of_study',
        ),
        migrations.AddField(
            model_name='university',
            name='course_level',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctorate', 'Doctorate')], default='undergraduate', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='field_of_study',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('medicine', 'Medicine'), ('arts', 'Arts & Humanities')], default='computer_science', max_length=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(choices=[('cagayan_de_oro', 'Cagayan de Oro'), ('philippines', 'Philippines'), ('asia', 'Asia')], default='cagayan_de_oro', max_length=100),
        ),
    ]
