# Generated by Django 5.2.1 on 2025-05-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
